image: atlassian/default-image:3

definitions:
  steps:
    - step: &build
        name: build
        image: node:18.12.1
        size: 2x
        caches:
          - node
        script:
          - npm install npm
          - npm install
          - npm run eslint
          - npm run build
          - echo "export WORK_DIR=$WORK_DIR" >> set_env.sh
          - echo "export SERVER=$SERVER" >> set_env.sh
        artifacts:
          - build/**
          - set_env.sh
    - step: &scp-deploy
        name: push
        script:
          - cat set_env.sh
          - source set_env.sh
          - pipe: atlassian/scp-deploy:0.3.12
            variables:
              USER: $USER
              SERVER: $SERVER
              REMOTE_PATH: '/var/www/${WORK_DIR}/web/$BITBUCKET_REPO_SLUG'
              LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/build'
pipelines:
  branches:
    dev:
      - step:
          <<: *build
          deployment: Develop
      - step:
          <<: *scp-deploy