export enum PageUrls {
  SignIn = '/sign-in',
  AccountType = '/account-type',
  SignUpPatient = '/sign-up-patient',
  SignUpDoctor = '/sign-up-doctor',
  SignUpCaregiver = '/sign-up-caregiver',
  EmailVerification = '/email-verification',
  MyAccount = '/my-account',
  ForgotPassword = '/forgot-password',
  ForgotPasswordConfirm = '/forgot-password/confirm',
  ForgotPasswordSuccess = '/forgot-password/success',
  Vitals = '/',
  VitalsPopup = '/2',
  GrantedUsers = '/granted-users',
  Requests = '/requests',
  Patients = '/',
  Patient = '/patient',
  EmergencyContacts = '/emergency-contacts',
  AccountRecovery = '/account-recovery',
}
