export enum PageUrls {
  SignIn = '/sign-in',
  AccountType = '/account-type',
  SignUpPatient = '/sign-up-patient',
  SignUpDoctor = '/sign-up-doctor',
  EmailVerification = '/email-verification',
  MyAccount = '/my-account',
  ForgotPassword = '/forgot-password',
  ForgotPasswordConfirm = '/forgot-password/confirm',
  ForgotPasswordSuccess = '/forgot-password/success',
  Vitals = '/vitals',
  MedicalDoctors = '/medical-doctors',
  Requests = '/requests',
  Patients = '/patients',
  Patient = '/patient',
  EmergencyContacts = '/emergency-contacts',
}
